version: '3.7'
services:
  python:
    build: .
    tty: true
    volumes:
      - ./app/:/app
    working_dir: /app
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dbt
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./app/:/app
volumes:
  data:
